services:
  - type: web
    name: feishu-delivery-sync
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FEISHU_APP_ID
        sync: false
      - key: FEISHU_APP_SECRET
        sync: false
      - key: FEISHU_APP_TOKEN
        sync: false
      - key: FEISHU_TABLE_ID
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO_OWNER
        sync: false
      - key: GITHUB_REPO_NAME
        sync: false 
      - key: GOOGLE_MAPS_API_KEY
        sync: false 